# Generated by Django 5.0.3 on 2024-03-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
