# Generated by Django 5.0.3 on 2024-03-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_detail',
            new_name='order',
        ),
    ]
